<a href="https://colab.research.google.com/github/21P31A0406/Python-libraries/blob/main/Pandas_MassCoders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importing Pandas**

In [ ]:
import pandas as pd
import numpy as np

# **Pandas**

**Pandas** is a powerful **Python library for data manipulation and analysis.** It provides easy-to-use data structures and functions to work with structured data like tabular, time series, or matrix data.

**Pandas primarily provides two data structures: Series and DataFrame.**

**Series:** A one-dimensional labeled array capable of holding any data type.

**DataFrame:** A two-dimensional labeled data structure with columns of potentially different types.

# **Pandas - Series**

**Series** in pandas is a fundamental data structure that represents a one-dimensional array of indexed data. It can hold any type of **data—integers, strings, floats, Python objects**, etc. The Series object is built on top of the NumPy array and is very similar to it but with additional capabilities like handling missing data. The indices of a pandas Series are more flexible than those in a simple NumPy array.

# Creating a Series

In [ ]:
s = pd.Series([1, 3, 5, 7, 9])
print(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64

**Key Attributes**

**Values:** The data in the Series.

**Index:** The index (labels) of each data point.

# **Common Methods of Series**

# Descriptive Statistics

**s.describe():** Provides a quick summary of the data.

This method gives a statistical summary of the Series, including count, mean, standard deviation, minimum, maximum, and quartile values.

In [ ]:
# Creating a Series
s = pd.Series([1, 3, 5, 7, 9])

# Descriptive statistics
print(s.describe())

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64

**s.mean():** Computes the mean of the data.

In [ ]:
# Mean of the Series
print(s.mean())

5.0

**s.std():** Computes the standard deviation.

In [ ]:
# Standard deviation of the Series
print(s.std())

3.1622776601683795

**s.min() and s.max():** Computes the minimum and maximum values.

In [ ]:
# Minimum and maximum values
print(s.min())
print(s.max())

1
9

# Data Manipulation

**s.map(func):** Applies a function to each element in the Series.

In [ ]:
# Mapping function to double the values
doubled = s.map(lambda x: x * 2)
print(doubled)

0     2
1     6
2    10
3    14
4    18
dtype: int64

**s.apply(func):** Similar to map, but more flexible. (Can be used Data Frames as well, where as map is only for Series)

In [ ]:
# Applying a function to calculate square root
sqrt = s.apply(lambda x: x ** 0.5)
print(sqrt)

0    1.000000
1    1.732051
2    2.236068
3    2.645751
4    3.000000
dtype: float64

**s.sort_values():** Sorts the Series.

In [ ]:
# Sorting the Series
sorted_s = s.sort_values()
print(sorted_s)

0    1
1    3
2    5
3    7
4    9
dtype: int64

**s.drop(labels):** Drops specified labels from the Series.

In [ ]:
# Dropping the first element
dropped = s.drop(0)
print(dropped)

1    3
2    5
3    7
4    9
dtype: int64

In [ ]:
print(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64

# Handling Missing Data

**s.isnull():** Checks for missing values, returns a Series of booleans.

In [ ]:
# Checking for missing values
print(s.isnull())

0    False
1    False
2    False
3    False
4    False
dtype: bool

**s.notnull():** Opposite of isnull().

In [ ]:
# Checking for non-null values
print(s.notnull())

0    True
1    True
2    True
3    True
4    True
dtype: bool

**s.fillna(value):** Fills missing values with a specified value.

In [ ]:
# Create a Series with missing values
s = pd.Series([1, 2, np.nan, 4, np.nan])

# Print the Series
print(s)

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [ ]:
# Filling missing values with 0
filled = s.fillna(9)
print(filled)

0    1.0
1    2.0
2    9.0
3    4.0
4    9.0
dtype: float64

**s.dropna():** Drops all rows that contain missing values.

In [ ]:
# Creating a Series with missing values
s_with_missing = pd.Series([1, 2, None, 4, 5])

# Dropping missing values
dropped_missing = s_with_missing.dropna()
print(dropped_missing)

0    1.0
1    2.0
3    4.0
4    5.0
dtype: float64

# Indexing, Slicing, and Filtering

**s.iloc[ ]:** Purely integer-location based indexing.

In [ ]:
# Indexing by position
s = pd.Series([1, 3, 5, 7, 9])
print(s.iloc[0])  # First element
print(s.iloc[-1])  # Last element

1
9

**s.loc[ ]:** Label-based indexing.

In [ ]:
# Indexing by label
print(s.loc[0])  # First element
print(s.loc[4])  # Last element

1
9

In [ ]:
# Create a Series
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s)
# Accessing elements using iloc
print(s.iloc[0])  # Access the first element
print(s.iloc[1:3])  # Access elements at positions 1 and 2 (exclusive of 3)

# Accessing elements using loc
print(s.loc['a'])  # Access the element with index label 'a'
print(s.loc['b':'c'])  # Access elements with index labels 'b' and 'c'

a    10
b    20
c    30
d    40
dtype: int64
10
b    20
c    30
dtype: int64
10
b    20
c    30
dtype: int64

**s[s > n]:** Filters and returns elements greater than n.

In [ ]:
# Filtering elements greater than 5
filtered = s[s > 5]
print(filtered)

3    7
4    9
dtype: int64

# Aggregation

**s.sum():** Sums up the values.

In [ ]:
# Sum of the Series
print(s.sum())

25

**s.cumsum():** Cumulative sum.

In [ ]:
# Cumulative sum of the Series
print(s)
print(s.cumsum())

0    1
1    3
2    5
3    7
4    9
dtype: int64
0     1
1     4
2     9
3    16
4    25
dtype: int64

**s.aggregate(func):** Aggregates using one or more operations.

In [ ]:
# Aggregating using multiple operations
aggregated = s.aggregate(['sum', 'mean', 'std'])
print(aggregated)

sum     25.000000
mean     5.000000
std      3.162278
dtype: float64

# Creating Data Frame

In [ ]:
# Define data
data = {
    'Name': ['Dodagatta Nihar', 'Vignesh', 'Maheshwar', 'Naman', 'Naveen', 'Shreya', 'Varsha', 'Varun'],
    'Role': ['Founder', 'Growth Manager', 'Community Manager', 'Community Manager', 'Community Manager',
             'Course Designer', 'Course Designer', 'Public Relations Manager'],
    'Phone Number': ['111-111-1111', '222-222-2222', '333-333-3333', '444-444-4444',
                     '555-555-5555', '666-666-6666', '777-777-7777', '888-888-8888'],
    'Email': ['nihar@masscoders.tech', 'vignesh@masscoders.tech', 'maheshwar@masscoders.tech', 'naman@masscoders.tech',
              'naveen@masscoders.tech', 'shreya@masscoders.tech', 'varsha@masscoders.tech', 'varun@masscoders.tech'],
    'Address': ['123, MG Road, Bangalore', '456, Brigade Road, Chennai', '789, Rajaji Nagar, Mumbai', '101, Indira Nagar, Delhi',
                '202, Koramangala, Hyderabad', '303, JP Nagar, Kolkata', '404, Electronic City, Pune', '505, HSR Layout, Ahmedabad'],
    'Blood Group': ['A+', 'B-', 'O+', 'AB+', 'A-', 'B+', 'O-', 'AB-']
}

# Create DataFrame
team_mass_coders_df = pd.DataFrame(data)

# Display DataFrame
team_mass_coders_df.head()

,Name,Role,Phone Number,Email,Address,Blood Group
0,Dodagatta Nihar,Founder,111-111-1111,nihar@masscoders.tech,"123, MG Road, Bangalore",A+
1,Vignesh,Growth Manager,222-222-2222,vignesh@masscoders.tech,"456, Brigade Road, Chennai",B-
2,Maheshwar,Community Manager,333-333-3333,maheshwar@masscoders.tech,"789, Rajaji Nagar, Mumbai",O+
3,Naman,Community Manager,444-444-4444,naman@masscoders.tech,"101, Indira Nagar, Delhi",AB+
4,Naveen,Community Manager,555-555-5555,naveen@masscoders.tech,"202, Koramangala, Hyderabad",A-

In [ ]:
team_mass_coders_df

,Name,Role,Phone Number,Email,Address,Blood Group
0,Dodagatta Nihar,Founder,111-111-1111,nihar@masscoders.tech,"123, MG Road, Bangalore",A+
1,Vignesh,Growth Manager,222-222-2222,vignesh@masscoders.tech,"456, Brigade Road, Chennai",B-
2,Maheshwar,Community Manager,333-333-3333,maheshwar@masscoders.tech,"789, Rajaji Nagar, Mumbai",O+
3,Naman,Community Manager,444-444-4444,naman@masscoders.tech,"101, Indira Nagar, Delhi",AB+
4,Naveen,Community Manager,555-555-5555,naveen@masscoders.tech,"202, Koramangala, Hyderabad",A-
5,Shreya,Course Designer,666-666-6666,shreya@masscoders.tech,"303, JP Nagar, Kolkata",B+
6,Varsha,Course Designer,777-777-7777,varsha@masscoders.tech,"404, Electronic City, Pune",O-
7,Varun,Public Relations Manager,888-888-8888,varun@masscoders.tech,"505, HSR Layout, Ahmedabad",AB-

# Merging Data Frames

In [ ]:
# Team roles data
roles_data = {
    'Name': ['Dodagatta Nihar', 'Vignesh', 'Maheshwar', 'Naman', 'Naveen', 'Shreya', 'Varsha', 'Varun'],
    'Role': ['Founder', 'Growth Manager', 'Community Manager', 'Community Manager', 'Community Manager',
             'Course Designer', 'Course Designer', 'Public Relations Manager']
}

roles_df = pd.DataFrame(roles_data)

# Contact information data
contact_data = {
    'Name': ['Dodagatta Nihar', 'Vignesh', 'Maheshwar', 'Naman', 'Naveen', 'Shreya', 'Varsha', 'Varun'],
    'Phone Number': ['111-111-1111', '222-222-2222', '333-333-3333', '444-444-4444',
                     '555-555-5555', '666-666-6666', '777-777-7777', '888-888-8888'],
    'Email': ['nihar@masscoders.tech', 'vignesh@masscoders.tech', 'maheshwar@masscoders.tech', 'naman@masscoders.tech',
              'naveen@masscoders.tech', 'shreya@masscoders.tech', 'varsha@masscoders.tech', 'varun@masscoders.tech']
}

contact_df = pd.DataFrame(contact_data)

In [ ]:
merged_df = pd.merge(roles_df, contact_df, on='Name')

In [ ]:
merged_df

,Name,Role,Phone Number,Email
0,Dodagatta Nihar,Founder,111-111-1111,nihar@masscoders.tech
1,Vignesh,Growth Manager,222-222-2222,vignesh@masscoders.tech
2,Maheshwar,Community Manager,333-333-3333,maheshwar@masscoders.tech
3,Naman,Community Manager,444-444-4444,naman@masscoders.tech
4,Naveen,Community Manager,555-555-5555,naveen@masscoders.tech
5,Shreya,Course Designer,666-666-6666,shreya@masscoders.tech
6,Varsha,Course Designer,777-777-7777,varsha@masscoders.tech
7,Varun,Public Relations Manager,888-888-8888,varun@masscoders.tech

# **Importing Dataset**

Importing datasets into Pandas is straightforward, and Pandas supports various file formats like csv, xlsx, json, sql etc.

In [ ]:
df = pd.read_csv('filmtv_movies.csv')

# Display the first few rows of the DataFrame to understand its structure and contents
df.head()

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

The dataset contains information about movies, represented in a DataFrame structure.

**filmtv_id:** A unique identifier for each movie.

**title:** The title of the movie.

**year:** The release year of the movie.

**genre:** The genre of the movie.

**duration:** The duration of the movie in minutes.

**country:** The country where the movie was produced.

**directors:** Names of the directors of the movie.

**actors:** Names of the main actors in the movie.

**avg_vote, critics_vote, public_vote:** Average ratings from different sources.

**total_votes:** Total number of votes the movie received.

**description:** A short description of the movie plot.

**notes:** Additional notes or commentary about the movie.

**humor, rhythm, effort, tension, erotism:** Various attributes rated on a scale (probably from 0 to a maximum value, representing different aspects of the movie).

# **Pandas - DataFrame**

# Properties of DataFrame

**df.head(n):**
The df.head(n) method is used to view the first n rows of the DataFrame. This is particularly useful for getting a quick snapshot of the data, especially to understand the structure and the types of data contained in each column. If you don't specify n, the default number of rows displayed is 5.

In [ ]:
df.head(10)  # Displays the first 10 rows of the DataFrame

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
5,21,The Uranian Conspiracy,1978,Spy,117,"Italy, Germany, Israel","Gianfranco Baldanello, Menahem Golan","Fabio Testi, Janet Agren, Assaf Dayan, Siegfri...",4.8,3.50,6.0,5,Two Israeli secret agents discover that traffi...,"Action and chases for half of Europe, espionag...",1,2,0,2,0
6,22,A ciascuno il suo,1967,Drama,93,Italy,Elio Petri,"Gian Maria Volonté, Irene Papas, Gabriele Ferz...",7.6,7.68,7.0,139,Investigations into two murders committed in a...,"Champion of the cinema of civil commitment, El...",0,2,3,3,1
7,23,Dead-Bang,1989,Crime,109,United States,John Frankenheimer,"Don Johnson, Penelope Ann Miller, William Fors...",6.0,6.00,6.0,27,"In the throes of a double murder, Jerry Beck, ...",When it comes to talking about mysterious plot...,0,2,0,2,1
8,24,A... come assassino,1966,Thriller,80,Italy,Ray Morrison (Angelo Dorigo),"Alan Steel, Mary Arden, Sergio Ciani, Ivano Da...",5.2,3.00,7.0,5,After a man's corpse is found by his niece in ...,Approximation and mediocrity in go-go.,1,2,0,1,0
9,26,At Close Range,1986,Drama,115,United States,James Foley,"Christopher Walken, Sean Penn, Chris Penn, Mar...",7.5,7.64,7.0,90,Young Brad (Penn) lives with his grandmother a...,"Powerful and brutal thriller, second work by J...",1,3,2,4,2

**df.tail(n):**
The df.tail(n) method is similar to df.head(n) but for the end of the DataFrame. It returns the last n rows. This is useful to see the most recent or the last few entries in your data, depending on the ordering of your dataset. Like df.head(n), the default value of n is 5 if it isn't specified.

In [ ]:
df.tail(10)  # Displays the last 10 rows of the DataFrame

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
41389,232184,Nowhere,2023,Thriller,109,Spain,Albert Pintó,"Anna Castillo, Tamar Novas",5.3,5.25,5.0,10,"Mia, pregnant, flees together with her husband...",NaN,0,0,0,0,0
41390,232203,Mes petites amoureuses,1974,Drama,123,France,Jean Eustache,"Martin Loeb, Jacqueline Dufranne, Jacques Roma...",8.3,8.50,8.0,3,Daniel is a silent boy who observes girls with...,NaN,0,0,0,0,0
41391,232755,Organ Trail,2023,Western,112,United States,Michael Patrick Jann,"Zoé De Grand Maison, Mather Zickel, Lisa LoCic...",5.0,5.50,5.0,8,The young abigale Archer is located alone in M...,NaN,0,0,0,0,0
41392,232757,Hidden Family Secrets,2021,Thriller,87,Canada,Stefan Brogren,"Alex Paxton-Beesley, Madelyn Keys, Sonja Smits...",5.3,NaN,5.0,3,"While struggling to try to save her daughter, ...",NaN,0,0,0,0,0
41393,232816,La stoccata vincente,2023,Biography,107,Italy,Nicola Campiotti,"Alessio Vassallo, Flavio Insinna, Elena Funari...",4.5,NaN,5.0,4,The true story of the prodigy of fencing Paolo...,Freely inspired by the book The winning fool b...,0,0,0,0,0
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

**df.shape:**
The df.shape attribute of a DataFrame returns a tuple representing the dimensionality of the DataFrame. The first element of the tuple is the number of rows, and the second is the number of columns. This is useful when you need to know how large the dataset is, such as when you are preprocessing data or ensuring that data manipulations have executed correctly.

In [ ]:
df.shape  # Outputs: (number of rows, number of columns)

(41399, 19)

**df.columns:**
The df.columns attribute returns an Index object containing the column labels of the DataFrame. Knowing the column names is essential for accessing specific data in the DataFrame, performing analyses, and for data manipulation tasks like sorting, filtering, or applying functions to certain columns.

In [ ]:
df.columns  # Lists all the column names in the DataFrame

Index(['filmtv_id', 'title', 'year', 'genre', 'duration', 'country',
       'directors', 'actors', 'avg_vote', 'critics_vote', 'public_vote',
       'total_votes', 'description', 'notes', 'humor', 'rhythm', 'effort',
       'tension', 'erotism'],
      dtype='object')

**Inspecting Data Types:** Each column in a DataFrame has a specific data type. Understanding these types is crucial for proper data manipulation

In [ ]:
# Display the data types of each column
df.dtypes

filmtv_id         int64
title            object
year              int64
genre            object
duration          int64
country          object
directors        object
actors           object
avg_vote        float64
critics_vote    float64
public_vote     float64
total_votes       int64
description      object
notes            object
humor             int64
rhythm            int64
effort            int64
tension           int64
erotism           int64
dtype: object

**Summary Statistics:** For numerical data, it's useful to get a sense of their central tendency and spread

In [ ]:
# Display summary statistics for numerical columns
df.describe()

,filmtv_id,year,duration,avg_vote,critics_vote,public_vote,total_votes,humor,rhythm,effort,tension,erotism
count,41399.000000,41399.000000,41399.000000,41399.000000,36703.000000,41205.000000,41399.000000,41399.000000,41399.000000,41399.000000,41399.000000,41399.000000
mean,57746.410179,1993.505302,100.537163,5.801522,5.796077,5.924135,36.986763,0.577381,1.345347,0.684847,0.919153,0.309814
std,59962.095730,23.685612,27.260962,1.403861,1.593062,1.480112,69.386853,0.899402,1.154829,1.112334,1.095410,0.645930
min,2.000000,1897.000000,41.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,15857.000000,1976.000000,90.000000,4.800000,4.670000,5.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,36266.000000,2001.000000,96.000000,5.900000,6.000000,6.000000,12.000000,0.000000,2.000000,0.000000,0.000000,0.000000
75%,70935.000000,2013.000000,107.000000,6.900000,7.000000,7.000000,36.000000,1.000000,2.000000,1.000000,2.000000,0.000000
max,232920.000000,2023.000000,1525.000000,10.000000,10.000000,10.000000,1082.000000,5.000000,5.000000,5.000000,5.000000,5.000000

# Accessing and Filtering:

**df.loc:**
The df.loc method is used for label-based indexing, meaning you can access rows and columns using their labels (i.e., index names and column names). It allows for selecting a subset of rows and columns from a DataFrame with powerful and flexible slicing, indexing, and filtering options.

In [ ]:
df.head(5)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [ ]:
# Selecting all rows and a specific column by label
titles = df.loc[:, 'title']
titles

0        Bugs Bunny's Third Movie: 1001 Rabbit Tales
1                          18 anni tra una settimana
2                                   Ride a Wild Pony
3                                              Diner
4                    A che servono questi quattrini?
                            ...
41394                             Gold Digger Killer
41395                            Addio al nubilato 2
41396                                    Konferensen
41397                                      Ballelina
41398                      Invitación a un Asesinato
Name: title, Length: 41399, dtype: object

In [ ]:
# Selecting a range of rows and multiple columns by labels
subset = df.loc[10:20, ['title', 'year', 'genre']]
subset

                                   title  year        genre
10             A Ghentar si muore facile  1968    Adventure
11               Sleeping with the Enemy  1990        Drama
12                   In Bed With Madonna  1990  Documentary
13                    Bowery at Midnight  1942       Horror
14  A mezzanotte va la ronda del piacere  1975       Comedy
15                          Mr. Majestyk  1974       Action
16                          Warning Sign  1985       Action
17                      About Last Night  1986       Comedy
18                             Fail-Safe  1964        Drama
19                      Some Like It Hot  1959       Comedy
20                    A qualsiasi prezzo  1968    Adventure

In [ ]:
# Conditional selection using a boolean array
dramas = df.loc[df['genre'] == 'Drama']
dramas

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
6,22,A ciascuno il suo,1967,Drama,93,Italy,Elio Petri,"Gian Maria Volonté, Irene Papas, Gabriele Ferz...",7.6,7.68,7.0,139,Investigations into two murders committed in a...,"Champion of the cinema of civil commitment, El...",0,2,3,3,1
9,26,At Close Range,1986,Drama,115,United States,James Foley,"Christopher Walken, Sean Penn, Chris Penn, Mar...",7.5,7.64,7.0,90,Young Brad (Penn) lives with his grandmother a...,"Powerful and brutal thriller, second work by J...",1,3,2,4,2
11,32,Sleeping with the Enemy,1990,Drama,96,United States,Joseph Ruben,"Julia Roberts, Patrick Bergin, Kevin Anderson,...",5.0,4.33,6.0,111,Martin and Laura Burney have been married for ...,"Some twist is actually well placed, but from a...",1,3,2,3,1
18,49,Fail-Safe,1964,Drama,110,United States,Sidney Lumet,"Henry Fonda, Dan O'Herlihy, Walter Matthau, Do...",8.2,8.20,8.0,73,When the US strategic air command is alerted t...,"With this film Lumet returns great, after a pe...",0,3,3,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41368,229838,Tereddüt Çizgisi,2023,Drama,84,"Turkey, France, Romania, Spain",Selman Nacar,"Tülin Özen, Görkem Ipek",7.0,7.00,7.0,3,All over a day. A criminal lawyer is awaiting ...,NaN,0,0,0,0,0
41370,229865,Stolen,2023,Drama,92,India,Karan Tejpal,"Abhishek Banerjee, Harish Khanna, Mia Maelzer,...",5.3,6.00,5.0,4,"The five -month daughter of Jhumpa Mahato, poo...",NaN,0,0,0,0,0
41371,229881,Árni,2023,Drama,103,Hungary,Dorka Vermes,"Péter Turi, Andrea Spolarics",5.3,6.00,5.0,3,A lone nomad who works for an itinerant circus...,NaN,0,0,0,0,0
41372,229883,Kanata no uta,2023,Drama,84,Japan,Kyoshi Sugita,"An Ogawa, Yûko Nakamura, Hidekazu Mashima",5.5,5.00,6.0,3,"The twenty -five year old Haru, committed in a...",NaN,0,0,0,0,0
41390,232203,Mes petites amoureuses,1974,Drama,123,France,Jean Eustache,"Martin Loeb, Jacqueline Dufranne, Jacques Roma...",8.3,8.50,8.0,3,Daniel is a silent boy who observes girls with...,NaN,0,0,0,0,0

In [ ]:
multiple_condition = df.loc[(df['genre'] == 'Drama') & (df['avg_vote']>7.0)]
multiple_condition

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
6,22,A ciascuno il suo,1967,Drama,93,Italy,Elio Petri,"Gian Maria Volonté, Irene Papas, Gabriele Ferz...",7.6,7.68,7.0,139,Investigations into two murders committed in a...,"Champion of the cinema of civil commitment, El...",0,2,3,3,1
9,26,At Close Range,1986,Drama,115,United States,James Foley,"Christopher Walken, Sean Penn, Chris Penn, Mar...",7.5,7.64,7.0,90,Young Brad (Penn) lives with his grandmother a...,"Powerful and brutal thriller, second work by J...",1,3,2,4,2
18,49,Fail-Safe,1964,Drama,110,United States,Sidney Lumet,"Henry Fonda, Dan O'Herlihy, Walter Matthau, Do...",8.2,8.20,8.0,73,When the US strategic air command is alerted t...,"With this film Lumet returns great, after a pe...",0,3,3,3,0
30,70,Can You Feel Me Dancing?,1986,Drama,120,United States,Michael Miller,"Justine Bateman, Jason Bateman, Max Gail, Joe ...",8.0,6.00,10.0,3,"Karin Nichols, blind since birth, no longer st...","Based on a true story, it is a film for televi...",0,2,2,0,0
44,92,Accattone,1961,Drama,120,Italy,Pier Paolo Pasolini,"Franco Citti, Franca Pasut, Adriana Asti, Paol...",8.4,8.81,8.0,299,"Story of a drifter, Accattone, who drags an em...",After seeing the first dailies Federico Fellin...,1,3,3,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41320,226639,Sambizanga,1972,Drama,97,"Angola, France",Sarah Maldoror,"Elisa Andrade, Jean M'Vondo, Dino Abelino, Ben...",7.5,7.50,8.0,4,"Angola, 1961. Domingos Xavier, an anti -coloni...",Taken from a true story told in the book in Vi...,0,0,0,0,0
41349,229784,The Burial,2023,Drama,126,United States,Maggie Betts,"Bill Camp, Jamie Foxx, Tommy Lee Jones, Alan R...",7.3,NaN,7.0,10,"With the help of two lawyers, a family struggl...",NaN,0,1,1,1,0
41355,229808,Aku wa sonzai shinai,2023,Drama,106,Japan,Ryûsuke Hamaguchi,"Hitoshi Omika, Ryo Nishikawa, Ryuji Kosaka, Ay...",7.2,7.00,7.0,9,"Takumi and his daughter Hana live in Mizubiki,...",NaN,0,0,0,0,0
41366,229832,Magyarázat mindenre,2023,Drama,151,"Hungary, Slovakia",Gábor Reisz,"Adonyi-Walsh Gáspár, István Znamenák, András R...",7.3,7.33,7.0,6,"A realistic portrait of a divided country, Hun...",NaN,0,0,0,0,0
41390,232203,Mes petites amoureuses,1974,Drama,123,France,Jean Eustache,"Martin Loeb, Jacqueline Dufranne, Jacques Roma...",8.3,8.50,8.0,3,Daniel is a silent boy who observes girls with...,NaN,0,0,0,0,0

**df.iloc:**
While df.loc uses labels for indexing, df.iloc allows for integer-based indexing. You use df.iloc to access rows and columns by their integer positions, which makes it useful when you need to access data by its position in the DataFrame.

In [ ]:
df.head(5)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [ ]:
# Selecting a single row from the DataFrame
single_row = df.iloc[0]
single_row

filmtv_id                                                       2
title                 Bugs Bunny's Third Movie: 1001 Rabbit Tales
year                                                         1982
genre                                                   Animation
duration                                                       76
country                                             United States
directors                    David Detiege, Art Davis, Bill Perez
actors                                                        NaN
avg_vote                                                      7.7
critics_vote                                                  8.0
public_vote                                                   7.0
total_votes                                                    22
description     With two protruding front teeth, a slightly sl...
notes           These are many small independent stories, whic...
humor                                                           3
rhythm                                                          3
effort                                                          0
tension                                                         0
erotism                                                         0
Name: 0, dtype: object

In [ ]:
# Selecting a specific row and columns by integer indices
specific_data = df.iloc[10, [1, 2, 3]]  # row at index 10 and columns at indices 1, 2, and 3
specific_data

title    A Ghentar si muore facile
year                          1968
genre                    Adventure
Name: 10, dtype: object

In [ ]:
# Slicing to get multiple rows and columns
multi_slice = df.iloc[10:15, 0:4]  # Rows 10 to 14 and columns 0 to 3
multi_slice

    filmtv_id                                 title  year        genre
10         30             A Ghentar si muore facile  1968    Adventure
11         32               Sleeping with the Enemy  1990        Drama
12         34                   In Bed With Madonna  1990  Documentary
13         36                    Bowery at Midnight  1942       Horror
14         37  A mezzanotte va la ronda del piacere  1975       Comedy

**df.at:**
df.at is designed to access a single value for a row/column label pair. It is very similar to df.loc for accessing scalar values but is optimized for faster access when you only need to get or set a single value in a DataFrame.

In [ ]:
# Access a specific single value using row label and column name
title_of_first_movie = df.at[0, 'title']
title_of_first_movie

"Bugs Bunny's Third Movie: 1001 Rabbit Tales"

**Filtering Based on Criteria:**
Filtering data based on specific criteria is a common operation in data analysis. Pandas provides several methods to perform these operations, often using boolean indexing.

In [ ]:
# Filter movies released after 2010
recent_movies = df[df['year'] > 2010]
recent_movies

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
22817,39955,The Tree of Life,2011,Drama,138,United States,Terrence Malick,"Brad Pitt, Sean Penn, Jessica Chastain, Tye Sh...",7.4,7.43,7.0,476,"Jack, an eleven-year-old boy, lives in the Mid...","Beauty passes through cinema: the director, as...",0,2,4,2,0
23725,41448,Season of the Witch,2011,Adventure,95,United States,Dominic Sena,"Nicolas Cage, Claire Foy, Ron Perlman, Stephen...",4.3,4.13,4.0,153,"During the fourteenth century, when the black ...",Thrown to the wind the attempts to build a bar...,1,2,1,3,0
24186,42398,Restless,2011,Drama,95,United States,Gus Van Sant,"Mia Wasikowska, Schuyler Fisk, Jane Adams, Lus...",6.9,6.59,7.0,151,Enoch is a 17-year-old who lost both parents a...,The director of Last Days returns to spy on th...,2,2,3,1,0
24426,42847,Qualunquemente,2011,Grotesque,96,Italy,Giulio Manfredonia,"Antonio Albanese, Sergio Rubini, Lorenza Indov...",5.6,5.65,6.0,291,Cetto La Qualunque (Albanese) returns to Italy...,The grotesque and at times effective mask rema...,4,3,3,1,1
24427,42848,Una sconfinata giovinezza,2011,Drama,98,Italy,Pupi Avati,"Fabrizio Bentivoglio, Francesca Neri, Serena G...",6.7,6.60,7.0,95,Lino Settembre and his wife Chicca lead a peac...,"Written with the taste of a novelist's plot, i...",2,2,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

In [ ]:
# Movies with a high public vote and specific genre
highly_rated_thrillers = df[(df['public_vote'] >= 8) & (df['genre'] == 'Thriller')]
highly_rated_thrillers

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
21,54,Johnny O'Clock,1947,Thriller,95,United States,Robert Rossen,"Dick Powell, Evelyn Keyes, Lee J. Cobb, Ellen ...",7.8,8.00,8.0,20,Johnny O'Clock (Powell) is a minority partner ...,Columbia took advantage of Dick Powell's recen...,1,3,1,3,1
27,67,You'll Like My Mother,1973,Thriller,94,United States,Lamont Johnson,"Patty Duke, Rosemary Murphy, Richard Thomas, S...",7.8,8.00,8.0,6,"After her husband's death, Francesca decides t...",Specialist Lamont Johnson has built an effecti...,0,3,1,3,0
140,236,Time Without Pity,1956,Thriller,88,Great Britain,Joseph Losey,"Michael Redgrave, Ann Todd, Peter Cushing, Joa...",7.9,8.00,8.0,16,Alec Graham was sentenced to death for killing...,Emigrated to Great Britain after being blackli...,0,3,2,3,0
183,296,Strangers on a Train,1951,Thriller,96,United States,Alfred Hitchcock,"Farley Granger, Robert Walker, Ruth Roman, Leo...",8.4,8.66,8.0,258,Guy Haines is a successful tennis player with ...,"Patricia Highsmith's first novel, that of the ...",1,2,2,4,0
302,478,Gaslight,1944,Thriller,109,United States,George Cukor,"Ingrid Bergman, Charles Boyer, Joseph Cotten, ...",7.8,7.86,8.0,94,"Paula married Gregory, who long ago strangled ...","Nice ""gothic"" melodrama by George Cukor. The m...",2,4,3,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40950,216918,Aru otoko,2022,Thriller,121,Japan,Kei Ishikawa,"Satoshi Tsumabuki, Sakura Andô, Masataka Kubot...",7.3,7.00,8.0,3,Akira works as a lawyer and one day he meets a...,NaN,0,0,0,0,0
41118,220183,The Other Child,2022,Thriller,114,South Korea,Jin-young Kim,"Kim Min-Jae, Hyo-ju Park",5.3,3.00,8.0,3,The members of a family deeply likes the disap...,NaN,0,0,0,0,0
41200,221403,Anatomie d'une chute,2023,Thriller,151,France,Justine Triet,"Sandra Hüller, Samuel Theis, Swann Arlaud, Jeh...",7.3,7.00,8.0,4,"Samuel is found dead, buried in the snow outsi...",NaN,0,0,0,0,0
41218,221890,Ming On,2022,Thriller,109,Hong Kong,Soi Cheang,"Ka-Tung Lam, Charm Man Chan, Wing-Sze Ng, Lok ...",7.8,8.00,8.0,4,"A master of fortune teller (Gordon Lam), very ...",NaN,0,0,0,0,0
41246,223251,Twisted Nerve,1968,Thriller,112,Great Britain,Roy Boulting,"Hayley Mills, Hywel Bennett, Billie Whitelaw, ...",7.5,7.00,8.0,3,Martin Durnley (Hywel Bennett) is a twenty yea...,NaN,0,0,0,0,0

In [ ]:
# Movies from a specific country
us_movies = df[df['country'] == 'United States']
us_movies

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
7,23,Dead-Bang,1989,Crime,109,United States,John Frankenheimer,"Don Johnson, Penelope Ann Miller, William Fors...",6.0,6.00,6.0,27,"In the throes of a double murder, Jerry Beck, ...",When it comes to talking about mysterious plot...,0,2,0,2,1
9,26,At Close Range,1986,Drama,115,United States,James Foley,"Christopher Walken, Sean Penn, Chris Penn, Mar...",7.5,7.64,7.0,90,Young Brad (Penn) lives with his grandmother a...,"Powerful and brutal thriller, second work by J...",1,3,2,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41377,231044,Shelter,2023,Thriller,91,United States,Anthony Nardolillo,"Cam Gigandet, Jaina Lee Ortiz, Lisa Vidal, Car...",3.7,4.00,3.0,7,"Annabel, leader of a secret organization engag...",NaN,1,1,1,1,0
41382,231556,To End All War: Oppenheimer & the Atomic Bomb,2023,Documentary,87,United States,Christopher Cassel,"J. Robert Oppenheimer, Kai Bird, Ellen Bradbur...",6.6,5.00,8.0,8,"The arrogance, genius and determination of a m...",NaN,0,0,0,0,0
41384,232066,Hostage House,2021,Horror,85,United States,David Benullo,"Jennifer Taylor, Justin C. Schilling, Julia Te...",4.8,NaN,5.0,4,An ambitious real estate agent and his daughte...,NaN,0,0,0,0,0
41385,232101,Fear the Night,2023,Horror,92,United States,Neil LaBute,"Maggie Q, Ito Aghayere, Philip Burke, James Ca...",3.5,3.00,4.0,5,Tes is a veteran of the war in Iraq invited to...,NaN,0,0,0,0,0
41391,232755,Organ Trail,2023,Western,112,United States,Michael Patrick Jann,"Zoé De Grand Maison, Mather Zickel, Lisa LoCic...",5.0,5.50,5.0,8,The young abigale Archer is located alone in M...,NaN,0,0,0,0,0

# Updating Rows and Columns

**df.drop:**
The .drop() method in pandas is used to remove rows or columns from a DataFrame. Its primary purpose is to drop specified labels from rows or columns.

**Parameters:**

**labels:** The row or column labels to drop.

**axis:** Specifies whether the labels refer to rows (axis=0) or columns (axis=1). By default, it's 0 (rows).

**index or columns:** An alternative way to specify the labels to drop, instead of using the labels parameter. It is equivalent to specifying axis=0 (for index) or axis=1 (for columns).

**inplace:** If True, the operation is done in place, meaning it modifies the DataFrame directly and returns None. If False or not specified, it returns a new DataFrame with the specified labels dropped.

In [ ]:
df.drop(labels='title',axis=1)

,filmtv_id,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

In [ ]:
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

**Direct Assignment:**
Directly assign a value to a specific column or even a cell in a DataFrame.

In [ ]:
df.at[0, 'year'] = 1983  # Changes the year of the first movie to 1983
df.head(5)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [ ]:
df['new_column'] = 'default value'  # Adds a new column with all entries set to 'default value'
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism,new_column
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,default value
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,default value
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,default value
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,default value
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,default value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,default value
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,default value
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0,default value
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,default value
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,default value

In [ ]:
df.drop(axis=1,labels='new_column',inplace=True)

In [ ]:
df.head(5)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

**Using loc for Conditional Updates:**
loc can be used to update rows and columns based on a condition.

In [ ]:
df.loc[df['year'] < 2000, 'classic'] = True  # Marks movies before 2000 as classic
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism,classic
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,True
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,True
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,True
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,True
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,NaN
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,NaN
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0,NaN
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,NaN
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,NaN

In [ ]:
df.loc[df['avg_vote'] > 6, ['top_rated', 'must_watch']] = [True, True] # Modifying multiple columns using loc

In [ ]:
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,description,notes,humor,rhythm,effort,tension,erotism,classic,top_rated,must_watch
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,True,True,True
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,True,True,True
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,True,NaN,NaN
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,True,True,True
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,True,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,NaN,NaN,NaN
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,NaN,NaN,NaN
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,A team building conference organized for a gro...,NaN,0,0,0,0,0,NaN,NaN,NaN
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,NaN,NaN,NaN
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,NaN,NaN,NaN

**Using apply Function:**
The apply function allows you to apply a function along an axis of the DataFrame.

In [ ]:
df['length_category'] = df['duration'].apply(lambda x: 'Long' if x > 120 else 'Short')
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,notes,humor,rhythm,effort,tension,erotism,classic,top_rated,must_watch,length_category
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1983,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,"These are many small independent stories, whic...",3,3,0,0,0,True,True,True,Short
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,"Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,True,True,True,Short
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,"""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,True,NaN,NaN,Short
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,True,True,True,Short
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,Taken from the play by Armando Curcio that the...,3,1,1,0,0,True,NaN,NaN,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,Freely taken from a true story.,0,0,0,0,0,NaN,NaN,NaN,Short
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,Bachelorette fare sequel (2021).,0,0,0,0,0,NaN,NaN,NaN,Short
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Short
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Short
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Short

In [ ]:
# Create a DataFrame with multiple Series
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}
num_data = pd.DataFrame(data)

In [ ]:
num_data

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
# Define a function to sum two Series
def sum_series(x, y):
    return x + y

# Apply the function on multiple Series using apply()
result = num_data.apply(lambda row: sum_series(row['A'], row['B']), axis=1)

# Print the result
print(result)

0    5
1    7
2    9
dtype: int64

**Updating Using map or replace:**
You can update a column based on a mapping dictionary or replace values.

In [ ]:
df['genre'].map({'Drama': 'Drama Film', 'Comedy': 'Comedy Film'}) # Mapping existing values to new ones

0                NaN
1         Drama Film
2                NaN
3        Comedy Film
4        Comedy Film
            ...
41394            NaN
41395    Comedy Film
41396            NaN
41397            NaN
41398            NaN
Name: genre, Length: 41399, dtype: object

In [ ]:
df['country'].replace('USA', 'United States', inplace=True) # Replacing specific values
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

**Adding New Columns Based on Calculations:**
You can create new columns based on calculations from existing columns.

In [ ]:
df['title_year'] = df['title'] + " (" + df['year'].astype(str) + ")" # Creating a new column by combining existing columns
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism,title_year
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,18 anni tra una settimana (1991)
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Ride a Wild Pony (1976)
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Diner (1982)
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,A che servono questi quattrini? (1942)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Gold Digger Killer (2021)
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Addio al nubilato 2 (2023)
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0,Konferensen (2023)
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Ballelina (2023)
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Invitación a un Asesinato (2023)

**Using assign to Create Columns:**
assign helps you add new columns to a DataFrame in a functional style.

In [ ]:
df = df.assign(
    is_older=lambda x: x['year'] < 2000,
    duration_hours=lambda x: x['duration'] / 60
) # Adding multiple new columns

In [ ]:
df

,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,...,description,notes,humor,rhythm,effort,tension,erotism,title_year,is_older,duration_hours
2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,...,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...,True,1.266667
3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,...,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,18 anni tra una settimana (1991),True,1.633333
17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,...,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Ride a Wild Pony (1976),True,1.516667
18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,...,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Diner (1982),True,1.583333
20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,...,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,A che servono questi quattrini? (1942),True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,...,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Gold Digger Killer (2021),False,1.450000
232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,...,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Addio al nubilato 2 (2023),False,1.500000
232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,...,A team building conference organized for a gro...,NaN,0,0,0,0,0,Konferensen (2023),False,1.666667
232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,...,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Ballelina (2023),False,1.533333
232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,...,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Invitación a un Asesinato (2023),False,1.533333

# Changing the name of Index
Pandas allows you to rename the index of a DataFrame or Series, which can help in making the index more informative or aligning it with new data requirements.

**Renaming the Index of a DataFrame:**

In [ ]:
df.index.names = ['movie_id']  # Renames the index to 'movie_id'

In [ ]:
df

,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,...,description,notes,humor,rhythm,effort,tension,erotism,title_year,is_older,duration_hours
movie_id,,,,,,,,,,,,,,,,,,,,,
2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,...,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...,True,1.266667
3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,...,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,18 anni tra una settimana (1991),True,1.633333
17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,...,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Ride a Wild Pony (1976),True,1.516667
18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,...,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Diner (1982),True,1.583333
20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,...,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,A che servono questi quattrini? (1942),True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,...,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Gold Digger Killer (2021),False,1.450000
232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,...,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Addio al nubilato 2 (2023),False,1.500000
232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,...,A team building conference organized for a gro...,NaN,0,0,0,0,0,Konferensen (2023),False,1.666667
232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,...,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Ballelina (2023),False,1.533333
232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,...,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Invitación a un Asesinato (2023),False,1.533333

**Renaming Column Indexes:**

In [ ]:
df.rename(columns={'year': 'release_year', 'title': 'movie_title'}, inplace=True)
df

,movie_title,release_year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,...,description,notes,humor,rhythm,effort,tension,erotism,title_year,is_older,duration_hours
movie_id,,,,,,,,,,,,,,,,,,,,,
2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,...,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...,True,1.266667
3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,...,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,18 anni tra una settimana (1991),True,1.633333
17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,...,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Ride a Wild Pony (1976),True,1.516667
18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,...,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Diner (1982),True,1.583333
20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,...,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,A che servono questi quattrini? (1942),True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,...,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Gold Digger Killer (2021),False,1.450000
232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,...,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Addio al nubilato 2 (2023),False,1.500000
232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,...,A team building conference organized for a gro...,NaN,0,0,0,0,0,Konferensen (2023),False,1.666667
232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,...,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Ballelina (2023),False,1.533333
232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,...,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Invitación a un Asesinato (2023),False,1.533333

# Display Options

In [ ]:
# Set maximum number of rows and columns to display
pd.set_option('display.max_rows', 7)
pd.set_option('display.max_columns', 5)

In [ ]:
df

,movie_title,release_year,...,is_older,duration_hours
movie_id,,,,,
2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,...,True,1.266667
3,18 anni tra una settimana,1991,...,True,1.633333
17,Ride a Wild Pony,1976,...,True,1.516667
...,...,...,...,...,...
232915,Konferensen,2023,...,False,1.666667
232919,Ballelina,2023,...,False,1.533333
232920,Invitación a un Asesinato,2023,...,False,1.533333

In [ ]:
# Reset Options
pd.reset_option('display')

In [ ]:
df

,movie_title,release_year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,...,description,notes,humor,rhythm,effort,tension,erotism,title_year,is_older,duration_hours
movie_id,,,,,,,,,,,,,,,,,,,,,
2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,...,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...,True,1.266667
3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,...,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,18 anni tra una settimana (1991),True,1.633333
17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,...,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Ride a Wild Pony (1976),True,1.516667
18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,...,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Diner (1982),True,1.583333
20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,...,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,A che servono questi quattrini? (1942),True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,...,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Gold Digger Killer (2021),False,1.450000
232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,...,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Addio al nubilato 2 (2023),False,1.500000
232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,...,A team building conference organized for a gro...,NaN,0,0,0,0,0,Konferensen (2023),False,1.666667
232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,...,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Ballelina (2023),False,1.533333
232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,...,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Invitación a un Asesinato (2023),False,1.533333

# Grouping Data:
Grouping data is a powerful way to perform segment-wise analysis and break down the dataset into chunks based on some criteria.

In [ ]:
genre_groups = df.groupby('genre')  # Groups the data by the 'genre' column
genre_groups

In [ ]:
for genre, group_data in genre_groups:
    print(f"Genre: {genre}")
    print(group_data)
    print()

Genre: Action
                   movie_title  release_year   genre  duration        country  \
movie_id
38                Mr. Majestyk          1974  Action       105  United States
45                Warning Sign          1985  Action        99  United States
193                Airport '77          1977  Action       110  United States
530        Wings of the Apache          1990  Action        86  United States
574       Geheimcode Wildgänse          1985  Action        93          Italy
...                        ...           ...     ...       ...            ...
225561      Tin joek yau ching          1990  Action        87      Hong Kong
226116            Blood & Gold          2023  Action       100        Germany
228408            Kung Fu Girl          2021  Action        98  United States
229097                 Hit Man          2023  Action       113  United States
231061              Sentinelle          2023  Action        99         France

                                 directors  \
movie_id
38                       Richard Fleischer
45                             Hal Barwood
193                          Jerry Jameson
530                            David Green
574                     Antonio Margheriti
...                                    ...
225561                          Benny Chan
226116                     Peter Thorwarth
228408             Devon Downs, Kenny Gage
229097                   Richard Linklater
231061    Hugo Benamozig, David Caviglioli

                                                     actors  avg_vote  \
movie_id
38        Charles Bronson, Linda Cristal, Al Lettieri, L...       6.2
45        Sam Waterston, Kathleen Quinlan, Yaphet Kotto,...       4.8
193       Jack Lemmon, James Stewart, Lee Grant, Brenda ...       4.7
530       Nicolas Cage, Sean Young, Tommy Lee Jones, Dal...       4.6
574       Lewis Collins, Lee Van Cleef, Ernest Borgnine,...       4.9
...                                                     ...       ...
225561    Andy Lau, Chien-lien Wu, Man-Tat Ng, Kwong-Leu...       7.5
226116    Jördis Triebel, Alexander Scheer, Robert Maase...       6.1
228408    Danny Kwok-Kwan Chan, Yixi Tao, Shuting Li, Xi...       4.5
229097    Adria Arjona, Glen Powell, Retta, Austin Ameli...       7.1
231061    Jonathan Cohen, Emmanuelle Bercot, Raphaël Que...       4.0

          critics_vote  public_vote  ...  \
movie_id                             ...
38                5.71          7.0  ...
45                4.00          6.0  ...
193               3.33          6.0  ...
530               4.00          5.0  ...
574               3.50          6.0  ...
...                ...          ...  ...
225561            7.00          8.0  ...
226116            5.67          7.0  ...
228408             NaN          5.0  ...
229097            7.00          7.0  ...
231061             NaN          4.0  ...

                                                description  \
movie_id
38        A veteran of Vietnam, Vince (Bronson) grows me...
45        Inside the Biotek laboratory, a renowned and r...
193       An elderly billionaire, on the occasion of an ...
530       Jake Preston, a helicopter pilot, is called to...
574       Captain Wesley (Lewis Collins), whose son died...
...                                                     ...
225561    During a bank robbery, the driver designated f...
226116    Spring of 1945, the last days of the Second Wo...
228408    The twelve year old Lisa suffers from the scho...
229097    Gary Johnson, police investigator, plays under...
231061    François Sentinelle leads a double life. Durin...

                                                      notes humor  rhythm  \
movie_id
38        Cliché screenplay (by Elmore Leonard) tailored...     0       4
45        It is a film that mixes "The invasion of the b...     0       2
193       The film is yet another variation on the catas...     0       2
530       Nothing to say about Nicolas Cage as a drug ag...     1       2
574                                                     NaN     0       2
...                                                     ...   ...     ...
225561                                                  NaN     0       0
226116                                                  NaN     0       0
228408                                                  NaN     0       0
229097                                                  NaN     0       0
231061                                                  NaN     0       0

          effort  tension  erotism                   title_year is_older  \
movie_id
38             3        3        0          Mr. Majestyk (1974)     True
45             1        1        0          Warning Sign (1985)     True
193            0        1        0           Airport '77 (1977)     True
530            0        1        1   Wings of the Apache (1990)     True
574            0        2        0  Geheimcode Wildgänse (1985)     True
...          ...      ...      ...                          ...      ...
225561         0        0        0    Tin joek yau ching (1990)     True
226116         0        0        0          Blood & Gold (2023)    False
228408         0        0        0          Kung Fu Girl (2021)    False
229097         0        0        0               Hit Man (2023)    False
231061         0        0        0            Sentinelle (2023)    False

          duration_hours
movie_id
38              1.750000
45              1.650000
193             1.833333
530             1.433333
574             1.550000
...                  ...
225561          1.450000
226116          1.666667
228408          1.633333
229097          1.883333
231061          1.650000

[2155 rows x 21 columns]

Genre: Adventure
                               movie_title  release_year      genre  duration  \
movie_id
30               A Ghentar si muore facile          1968  Adventure       101
53                      A qualsiasi prezzo          1968  Adventure        94
74                                The Deep          1977  Adventure       130
145                         Africa Express          1975  Adventure        95
146                    Africa sotto i mari          1952  Adventure        95
...                                    ...           ...        ...       ...
222074                     We Have a Ghost          2023  Adventure       126
222398            Tremors: Shrieker Island          2020  Adventure       103
224588               Knights of the Zodiac          2023  Adventure       112
225497    Coast Guard Malaysia: Ops Helang          2023  Adventure        90
227960                       Hidden Strike          2023  Adventure       102

                                country           directors  \
movie_id
30                                Italy      Leon Klimovsky
53                                Italy     Emilio Miraglia
74                        United States         Peter Yates
145                               Italy        Michele Lupo
146                               Italy   Giovanni Roccardi
...                                 ...                 ...
222074                    United States  Christopher Landon
222398                    United States    Don Michael Paul
224588    Japan, Hungary, United States     Tomasz Baginski
225497                         Malaysia          Pitt Hanif
227960             China, United States         Scott Waugh

                                                     actors  avg_vote  \
movie_id
30        George Hilton, Ennio Girolami, Marta Padovan, ...       4.8
53        Walter Pidgeon, Ira Fürstenberg, Klaus Kinski,...       3.8
74        Nick Nolte, Jacqueline Bisset, Robert Shaw, El...       5.3
145       Giuliano Gemma, Ursula Andress, Jack Palance, ...       5.1
146       Sophia Loren, Stephen Barclay, Umberto Melnati...       4.1
...                                                     ...       ...
222074    Jennifer Coolidge, David Harbour, Anthony Mack...       6.2
222398    Michael Gross, Jon Heder, Richard Brake, Carol...       5.6
224588    Famke Janssen, Sean Bean, Madison Iseman, Mark...       3.4
225497    Saharul Ridzwan, Julia Farhana Marin, Sabri Yu...       3.5
227960    Jackie Chan, John Cena, Pilou Asbæk, Rachael H...       6.0

          critics_vote  public_vote  ...  \
movie_id                             ...
30                4.50          5.0  ...
53                4.00          4.0  ...
74                4.88          6.0  ...
145               5.50          5.0  ...
146               4.00          4.0  ...
...                ...          ...  ...
222074            6.00          6.0  ...
222398            5.00          6.0  ...
224588            3.00          4.0  ...
225497            3.00          4.0  ...
227960             NaN          6.0  ...

                                                description  \
movie_id
30        An adventurer juggles a dictator and a group o...
53        The holidays of Professor Cummings, an illustr...
74        A boy and a girl, passionate divers, dive off ...
145       John Baxter (Gemma) has been working in Africa...
146       In the Red Sea, a group of men is engaged in a...
...                                                     ...
222074    Kevin and his family suddenly become famous on...
222398    The adventurous entrepreneur Bill - together w...
224588    When a goddess of the war reincarnates in the ...
225497    Hafiz, the Malaysian Coast Guard officer, cele...
227960    In the near future, a group of civilians is fo...

                                                      notes humor  rhythm  \
movie_id
30                                                      NaN     0       2
53        Although Emilio Miraglia is blind (in cinemati...     1       2
74        Not very exciting, but the underwater scenes a...     1       2
145       The film had a notable success with the public...     1       2
146       Except for the presence of Sophia Loren, the b...     0       1
...                                                     ...   ...     ...
222074                                                  NaN     0       0
222398                                                  NaN     0       0
224588                                                  NaN     1       1
225497                                                  NaN     0       0
227960                                                  NaN     0       0

          effort  tension  erotism                               title_year  \
movie_id
30             0        1        0         A Ghentar si muore facile (1968)
53             0        1        1                A qualsiasi prezzo (1968)
74             1        2        1                          The Deep (1977)
145            0        1        1                    Africa Express (1975)
146            0        1        2               Africa sotto i mari (1952)
...          ...      ...      ...                                      ...
222074         0        0        0                   We Have a Ghost (2023)
222398         0        0        0          Tremors: Shrieker Island (2020)
224588         0        0        0             Knights of the Zodiac (2023)
225497         0        0        0  Coast Guard Malaysia: Ops Helang (2023)
227960         0        0        0                     Hidden Strike (2023)

         is_older  duration_hours
movie_id
30           True        1.683333
53           True        1.566667
74           True        2.166667
145          True        1.583333
146          True        1.583333
...           ...             ...
222074      False        2.100000
222398      False        1.716667
224588      False        1.866667
225497      False        1.500000
227960      False        1.700000

[1524 rows x 21 columns]

Genre: Animation
                                          movie_title  release_year  \
movie_id
2         Bugs Bunny's Third Movie: 1001 Rabbit Tales          1982
260                              The Land Before Time          1988
271                                Allegro non troppo          1977
679                      Asterix et le coup de menhir          1989
1093                               The Secret Of Nimh          1982
...                                               ...           ...
223768    Teenage Mutant Ninja Turtles: Mutant Mayhem          2023
223769                            The First Slam Dunk          2022
224224                   Ruby Gillman, Teenage Kraken          2023
229395                    Lonely Castle in the Mirror          2022
229825                                        Invelle          2023

              genre  duration        country  \
movie_id
2         Animation        76  United States
260       Animation        79  United States
271       Animation        85          Italy
679       Animation        81         France
1093      Animation        82  United States
...             ...       ...            ...
223768    Animation        99  United States
223769    Animation       124          Japan
224224    Animation        91  United States
229395    Animation       116          Japan
229825    Animation        96          Italy

                                     directors  \
movie_id
2         David Detiege, Art Davis, Bill Perez
260                                  Don Bluth
271                             Bruno Bozzetto
679                           Philippe Grimond
1093                                 Don Bluth
...                                        ...
223768                 Jeff Rowe, Kyler Spears
223769          Takehiko Inoue, Yasuyuki Ebara
224224                            Kirk DeMicco
229395         Keiichi Hara, Takakazu Nagatomo
229825                            Simone Massi

                                                     actors  avg_vote  \
movie_id
2                                                       NaN       7.7
260                                                     NaN       7.4
271       Maurizio Nichetti, Maurizio Micheli, Maria Lui...       7.6
679                                                     NaN       6.8
1093                                                    NaN       8.2
...                                                     ...       ...
223768                                                  NaN       6.4
223769                                                  NaN       8.0
224224                                                  NaN       6.0
229395                                                  NaN       6.7
229825                                                  NaN       9.0

          critics_vote  public_vote  ...  \
movie_id                             ...
2                 8.00          7.0  ...
260               7.50          7.0  ...
271               7.71          8.0  ...
679               6.67          7.0  ...
1093              8.50          8.0  ...
...                ...          ...  ...
223768            6.50          6.0  ...
223769             NaN          8.0  ...
224224            7.00          5.0  ...
229395            6.50          7.0  ...
229825            8.50         10.0  ...

                                                description  \
movie_id
2         With two protruding front teeth, a slightly sl...
260       A group of herbivorous dinosaurs of the "Colli...
271       A director wants to make an animated film base...
679       In Gaul subjugated by the Romans only the vill...
1093      Brisby, a widowed mouse, lives in a field with...
...                                                     ...
223768    After years spent in the sewers hiding from hu...
223769    Ryota Miyagi has an older, sota, three -year -...
224224    A shy teenager discovers that he comes from a ...
229395    In a quiet district of Tokyo, seven students j...
229825    1918. Zelinda is a peasant child orphaned moth...

                                                      notes humor  rhythm  \
movie_id
2         These are many small independent stories, whic...     3       3
260       With Ralph Bakshi, Don Bluth (who actually cut...     3       3
271       Debussy's "Prelude to the afternoon of a faun"...     2       3
679                                                     NaN     3       3
1093      After a long experience at Disney, Don Bluth w...     2       2
...                                                     ...   ...     ...
223768                                                  NaN     0       0
223769           Based on Takehiko Inoue's Slam Dunk manga.     0       0
224224                                                  NaN     0       0
229395                                                  NaN     0       0
229825                                                  NaN     0       0

          effort  tension  erotism  \
movie_id
2              0        0        0
260            0        1        0
271            2        0        0
679            0        0        0
1093           0        2        0
...          ...      ...      ...
223768         0        0        0
223769         0        0        0
224224         0        0        0
229395         1        1        1
229825         0        0        0

                                                 title_year is_older  \
movie_id
2         Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...     True
260                             The Land Before Time (1988)     True
271                               Allegro non troppo (1977)     True
679                     Asterix et le coup de menhir (1989)     True
1093                              The Secret Of Nimh (1982)     True
...                                                     ...      ...
223768    Teenage Mutant Ninja Turtles: Mutant Mayhem (2...    False
223769                           The First Slam Dunk (2022)    False
224224                  Ruby Gillman, Teenage Kraken (2023)    False
229395                   Lonely Castle in the Mirror (2022)    False
229825                                       Invelle (2023)    False

          duration_hours
movie_id
2               1.266667
260             1.316667
271             1.416667
679             1.350000
1093            1.366667
...                  ...
223768          1.650000
223769          2.066667
224224          1.516667
229395          1.933333
229825          1.600000

[1076 rows x 21 columns]

Genre: Biblical
                                 movie_title  release_year     genre  \
movie_id
942                                  Ben Hur          1959  Biblical
2119                    The Ten Commandments          1956  Biblical
2531                         Erode il Grande          1958  Biblical
3151                     Giuditta e Oloferne          1958  Biblical
3167           Giuseppe venduto dai fratelli          1961  Biblical
4274                               Il Messia          1975  Biblical
5347            The Greatest Story Ever Told          1965  Biblical
5854                       The King of Kings          1961  Biblical
6677                     La spada e la croce          1959  Biblical
6836                       The Story of Ruth          1960  Biblical
7372                                The Robe          1953  Biblical
9031                       Solomon and Sheba          1959  Biblical
10368                          David e Golia          1959  Biblical
12762     Genesi - La Creazione e il Diluvio          1994  Biblical
12825                          Ester e il re          1960  Biblical
16849                                 Esther          1985  Biblical
17935                           Il quarto re          1997  Biblical
19554                        Maria Maddalena          2000  Biblical
21090                                  Giuda          2000  Biblical
21135                                Tommaso          2001  Biblical
21910                   Giuseppe di Nazareth          1999  Biblical

In [ ]:
year_genre_groups = df.groupby(['release_year', 'genre'])  # Groups by year and genre

# Aggregation

After grouping, you might want to perform aggregation operations like sum, mean, count, etc., to summarize the data.

In [ ]:
# Simple Aggregation - Calculating the Average
avg_duration_by_genre = df.groupby('genre')['duration'].mean()  # Average duration per genre
print(avg_duration_by_genre)

genre
Action             101.682599
Adventure          102.870079
Animation           88.925651
Biblical           137.210526
Biography          120.602920
Comedy              97.881409
Crime               98.939914
Documentary         92.641638
Drama              105.271266
Erotico             90.893617
Fantasy            105.612326
Gangster           117.803571
Grotesque           99.851852
History            127.159420
Horror              92.603867
Musical            106.240654
Mythology           97.969697
Mélo               107.836538
Noir                98.428571
Romantic            94.778571
Sci-Fi             102.097238
Short Movie        210.500000
Sperimental         97.716049
Sport               95.428571
Spy                105.333333
Stand-up Comedy     73.000000
Super-hero         121.855422
Thriller            97.957849
War                111.306173
Western             95.800175
Name: duration, dtype: float64

In [ ]:
# Multiple Aggregations on a Single Column
stats_by_genre = df.groupby('genre')['avg_vote'].agg([np.mean, np.std, np.min, np.max])
print(stats_by_genre)

                     mean       std  min   max
genre
Action           5.123898  1.399433  1.0   9.0
Adventure        5.545866  1.324040  1.4   9.3
Animation        6.118030  1.281681  1.6   9.3
Biblical         5.184211  1.273753  2.9   8.2
Biography        5.949051  1.208300  1.0  10.0
Comedy           5.482645  1.355306  1.0  10.0
Crime            6.142918  1.167942  2.7   8.8
Documentary      6.564749  1.180058  1.0  10.0
Drama            6.292677  1.302034  1.0  10.0
Erotico          4.052766  1.323337  1.0   7.9
Fantasy          5.486282  1.322481  1.3   9.4
Gangster         6.614286  1.383333  2.5   9.0
Grotesque        6.458848  1.250535  2.3   9.1
History          5.887681  1.245398  2.7   8.8
Horror           5.225874  1.301247  1.3   9.1
Musical          6.016121  1.474926  1.8   9.0
Mythology        4.631818  1.298183  2.2   8.0
Mélo             6.715385  1.256731  3.6   8.6
Noir             6.985294  1.104915  3.4   9.5
Romantic         4.883367  1.532141  1.0   8.8
Sci-Fi           5.484309  1.365001  1.4   9.2
Short Movie      6.800000  0.843801  5.3   7.7
Sperimental      6.547531  1.170454  2.0   9.0
Sport            5.228571  1.879463  3.0   7.5
Spy              5.769167  1.399898  2.0   8.8
Stand-up Comedy  7.325000  0.793200  6.8   8.5
Super-hero       5.833735  1.032671  2.3   7.5
Thriller         5.530586  1.264825  1.0   9.3
War              6.293086  1.301066  1.7   9.3
Western          5.744590  1.306447  1.5   8.9

In [ ]:
# Different Aggregations for Different Columns
complex_aggregation = df.groupby('genre').agg({
    'duration': np.mean,  # average duration
    'avg_vote': [np.min, np.max],  # min and max average votes
    'public_vote': 'sum'  # total of public votes
})

In [ ]:
complex_aggregation

                   duration avg_vote       public_vote
                       mean      min   max         sum
genre
Action           101.682599      1.0   9.0     11369.0
Adventure        102.870079      1.4   9.3      8747.0
Animation         88.925651      1.6   9.3      6639.0
Biblical         137.210526      2.9   8.2       202.0
Biography        120.602920      1.0  10.0      4136.0
Comedy            97.881409      1.0  10.0     51634.0
Crime             98.939914      2.7   8.8      2953.0
Documentary       92.641638      1.0  10.0     13371.0
Drama            105.271266      1.0  10.0     76234.0
Erotico           90.893617      1.0   7.9       981.0
Fantasy          105.612326      1.3   9.4      2830.0
Gangster         117.803571      2.5   9.0       378.0
Grotesque         99.851852      2.3   9.1      1578.0
History          127.159420      2.7   8.8       823.0
Horror            92.603867      1.3   9.1     12917.0
Musical          106.240654      1.8   9.0      2647.0
Mythology         97.969697      2.2   8.0       338.0
Mélo             107.836538      3.6   8.6       705.0
Noir              98.428571      3.4   9.5      1640.0
Romantic          94.778571      1.0   8.8      4906.0
Sci-Fi           102.097238      1.4   9.2      5064.0
Short Movie      210.500000      5.3   7.7        41.0
Sperimental       97.716049      2.0   9.0      1018.0
Sport             95.428571      3.0   7.5        37.0
Spy              105.333333      2.0   8.8      1406.0
Stand-up Comedy   73.000000      6.8   8.5        32.0
Super-hero       121.855422      2.3   7.5       488.0
Thriller          97.957849      1.0   9.3     21048.0
War              111.306173      1.7   9.3      2596.0
Western           95.800175      1.5   8.9      6739.0

**Aggregating Without Grouping:**
Sometimes, you may want to perform aggregations without the need to group the data.

In [ ]:
# Overall Summary Statistics
overall_stats = df[['duration', 'avg_vote']].describe()
overall_stats

           duration      avg_vote
count  41399.000000  41399.000000
mean     100.537163      5.801522
std       27.260962      1.403861
min       41.000000      1.000000
25%       90.000000      4.800000
50%       96.000000      5.900000
75%      107.000000      6.900000
max     1525.000000     10.000000

**df.count():** This method returns the number of non-null values in each DataFrame column. It can be used to count the number of non-null values in each column individually.

In [ ]:
# Create a DataFrame
data = {'A': [1, 2, None], 'B': [4, None, 6], 'C': [5, 8, 9]}
data_df = pd.DataFrame(data)

# Count non-null values in each column
counts = data_df.count()
print(counts)

A    2
B    2
C    3
dtype: int64

**df.value_counts():** This method returns the frequency counts of unique values in a Series. It is typically used on a single column of the DataFrame and is useful for analyzing the distribution of values within that column.

In [ ]:
# Value Counts
df['movie_title'].value_counts()

movie_title
Les Vampires                 10
Pinocchio                     8
Riget II                      6
Dr. Jekyll and Mr. Hyde       5
Sibiriada                     5
                             ..
Farelavita                    1
A, B, C... Manhattan          1
Parfait amour!                1
A Season for Miracles         1
Invitación a un Asesinato     1
Name: count, Length: 39531, dtype: int64

**Custom Aggregation Functions:**
Pandas allows you to define and use custom aggregation functions for more specific data analysis needs.

In [ ]:
# Using a Custom Function for Aggregation
def range_func(series):
    return series.max() - series.min()

range_by_genre = df.groupby('genre')['duration'].agg(range_func)  # Range of durations by genre
range_by_genre

genre
Action              197
Adventure           355
Animation          1129
Biblical            330
Biography           267
Comedy              558
Crime               135
Documentary         859
Drama              1484
Erotico              61
Fantasy             202
Gangster            245
Grotesque           236
History             560
Horror              213
Musical             247
Mythology           104
Mélo                151
Noir                110
Romantic            150
Sci-Fi              259
Short Movie         487
Sperimental         774
Sport                34
Spy                 115
Stand-up Comedy      27
Super-hero          101
Thriller            550
War                 655
Western             145
Name: duration, dtype: int64

**Renaming Grouped Aggregation Results:**
It is often useful to rename the results of aggregations for clarity or further analysis.

In [ ]:
# Renaming Aggregation Results
renamed_aggregations = df.groupby('genre')['avg_vote'].agg([
    ('Average Rating', 'mean'),  # Renames the mean result to 'Average Rating'
    ('Rating Standard Deviation', 'std')  # Renames the std result to 'Rating Standard Deviation'
])
renamed_aggregations

                 Average Rating  Rating Standard Deviation
genre
Action                 5.123898                   1.399433
Adventure              5.545866                   1.324040
Animation              6.118030                   1.281681
Biblical               5.184211                   1.273753
Biography              5.949051                   1.208300
Comedy                 5.482645                   1.355306
Crime                  6.142918                   1.167942
Documentary            6.564749                   1.180058
Drama                  6.292677                   1.302034
Erotico                4.052766                   1.323337
Fantasy                5.486282                   1.322481
Gangster               6.614286                   1.383333
Grotesque              6.458848                   1.250535
History                5.887681                   1.245398
Horror                 5.225874                   1.301247
Musical                6.016121                   1.474926
Mythology              4.631818                   1.298183
Mélo                   6.715385                   1.256731
Noir                   6.985294                   1.104915
Romantic               4.883367                   1.532141
Sci-Fi                 5.484309                   1.365001
Short Movie            6.800000                   0.843801
Sperimental            6.547531                   1.170454
Sport                  5.228571                   1.879463
Spy                    5.769167                   1.399898
Stand-up Comedy        7.325000                   0.793200
Super-hero             5.833735                   1.032671
Thriller               5.530586                   1.264825
War                    6.293086                   1.301066
Western                5.744590                   1.306447